# Generated by Django 2.2.4 on 2019-09-04 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecocharte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine_charte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Proposition_charte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('explication', models.TextField(blank=True)),
                ('compteur_plus', models.IntegerField(default=0)),
                ('compteur_moins', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecocharte.Domaine_charte')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='type_message',
            field=models.CharField(choices=[('0', 'Commentaire'), ('1', 'Coquille'), ('2', 'Réflexion')], default='0', max_length=10, verbose_name='type de commentaire'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vote', models.CharField(choices=[(0, 'neutre'), (1, 'plus'), (2, 'moins')], default='0', max_length=10, verbose_name='type de commentaire')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecocharte.Proposition_charte')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire_charte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('type_message', models.CharField(choices=[('0', 'Commentaire'), ('1', 'Coquille'), ('2', 'Réflexion')], default='0', max_length=10, verbose_name='type de commentaire')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecocharte.Proposition_charte')),
            ],
        ),
    ]
