# Generated by Django 2.2.4 on 2019-09-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocharte', '0002_auto_20190904_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaine_charte',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proposition_charte',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
